# Permalinks
permalink:           pretty

# Setup
title:               Rachel ZQ. Zheng
tagline:             ¡°Stay hungry, stay foolish.¡±
url:                 http://ZeeTsing.github.io
paginate:            2
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Rachel Zhiqing Zheng
  url:               https://github.com/ZeeTsing
  email:             rachelzqzheng@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/ZeeTsing

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist

# Page List
pages_list:       
  About me: '/about'
  Archive: '/archive'
  Feed: '/index.html'
